// Block definitions — the JSON shapes for every custom block, registered with
// Blockly at module load (side-effect import). Pure data + the one register call;
// the block→JS generators live in blocks-generators.js, the toolbox + workspace
// adapter in blocks.js.
import * as Blockly from 'blockly';

// ── Block definitions ────────────────────────────────────────────────────────

Blockly.defineBlocksWithJsonArray([
  // ── Control ────────────────────────────────────────────────────────────────
  {
    type: 'ctrl_interval',
    message0: 'every %1 ms',
    args0: [{ type: 'field_number', name: 'MS', value: 100, min: 1 }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 120,
    tooltip: 'Repeat code every N milliseconds',
  },
  {
    type: 'ctrl_timeout',
    message0: 'after %1 ms',
    args0: [{ type: 'field_number', name: 'MS', value: 1000, min: 0 }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 120,
    tooltip: 'Run code once after N milliseconds',
  },
  {
    type: 'ctrl_onkey',
    message0: 'when key %1 pressed',
    args0: [
      {
        type: 'field_dropdown',
        name: 'KEY',
        options: [
          ['↑', 'ArrowUp'],
          ['↓', 'ArrowDown'],
          ['←', 'ArrowLeft'],
          ['→', 'ArrowRight'],
          ['Space', ' '],
          ['Enter', 'Enter'],
          ['Escape', 'Escape'],
          ['any', 'any'],
        ],
      },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 120,
    tooltip: 'Run code when a key is pressed',
  },
  {
    type: 'ctrl_stop',
    message0: 'stop program',
    previousStatement: null,
    nextStatement: null,
    colour: 0,
  },
  {
    type: 'ctrl_pause',
    message0: 'pause',
    previousStatement: null,
    nextStatement: null,
    colour: 30,
  },
  {
    type: 'ctrl_resume',
    message0: 'resume',
    previousStatement: null,
    nextStatement: null,
    colour: 30,
  },
  {
    type: 'ctrl_random',
    message0: 'random %1 to %2',
    args0: [
      { type: 'field_number', name: 'LO', value: 0 },
      { type: 'field_number', name: 'HI', value: 100 },
    ],
    output: 'Number',
    colour: 230,
    tooltip: 'Random number between lo and hi',
  },
  {
    type: 'ctrl_random_color',
    message0: 'random color',
    output: 'String',
    colour: 230,
    tooltip: 'A random vivid HSL color string',
  },

  // ── Audio ──────────────────────────────────────────────────────────────────
  {
    type: 'audio_create_synth',
    message0: 'create %1 synth',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['synth', 'synth'],
          ['polyphonic', 'poly'],
          ['FM', 'fm'],
          ['AM', 'am'],
          ['pluck', 'pluck'],
          ['kick', 'kick'],
          ['metal', 'metal'],
          ['noise', 'noise'],
        ],
      },
    ],
    output: null,
    colour: 260,
    tooltip: 'Create a synthesizer — store in a variable',
  },
  {
    type: 'audio_play',
    message0: 'play %1 for %2 on %3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'NOTE',
        options: [
          ['C3', 'C3'],
          ['D3', 'D3'],
          ['E3', 'E3'],
          ['G3', 'G3'],
          ['A3', 'A3'],
          ['C4', 'C4'],
          ['D4', 'D4'],
          ['E4', 'E4'],
          ['F4', 'F4'],
          ['G4', 'G4'],
          ['A4', 'A4'],
          ['B4', 'B4'],
          ['C5', 'C5'],
          ['D5', 'D5'],
          ['E5', 'E5'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'DUR',
        options: [
          ['whole', '1n'],
          ['half', '2n'],
          ['quarter', '4n'],
          ['eighth', '8n'],
          ['sixteenth', '16n'],
        ],
      },
      { type: 'input_value', name: 'SYNTH' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Play a note on a synth',
  },
  {
    type: 'audio_bpm',
    message0: 'set BPM to %1',
    args0: [{ type: 'field_number', name: 'BPM', value: 120, min: 1, max: 300 }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
  },
  {
    type: 'mixer_show',
    message0: 'open mixer',
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Open the live audio mixer console',
  },
  {
    type: 'mixer_volume',
    message0: 'mixer: set %1 volume to %2 dB',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'lead' },
      { type: 'field_number', name: 'DB', value: 0, min: -48, max: 6 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Set a mixer strip volume (use "master" for the master strip)',
  },
  {
    type: 'mixer_pan',
    message0: 'mixer: set %1 pan to %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'lead' },
      { type: 'field_number', name: 'PAN', value: 0, min: -1, max: 1, precision: 0.05 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Pan a mixer strip (-1 left … 1 right)',
  },
  {
    type: 'mixer_mute',
    message0: 'mixer: %1 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'STATE',
        options: [
          ['mute', 'true'],
          ['unmute', 'false'],
        ],
      },
      { type: 'field_input', name: 'NAME', text: 'lead' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Mute or unmute a mixer strip',
  },
  {
    type: 'audio_transport_start',
    message0: 'start transport',
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Start the audio transport clock — required for sequence and loop',
  },
  {
    type: 'audio_volume',
    message0: 'set master volume %1 dB',
    args0: [{ type: 'field_number', name: 'DB', value: -6, min: -60, max: 6 }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
  },
  {
    type: 'audio_reverb',
    message0: 'reverb %1 sec',
    args0: [{ type: 'field_number', name: 'DEC', value: 2, min: 0.1, max: 30 }],
    output: null,
    colour: 260,
    tooltip: 'Create a reverb effect — connect an instrument to it',
  },
  {
    type: 'audio_delay',
    message0: 'delay %1 sec feedback %2',
    args0: [
      { type: 'field_number', name: 'TIME', value: 0.25, min: 0.01 },
      { type: 'field_number', name: 'FB', value: 0.5, min: 0, max: 0.99 },
    ],
    output: null,
    colour: 260,
    tooltip: 'Create a feedback delay effect',
  },
  {
    type: 'audio_distort',
    message0: 'distortion %1',
    args0: [{ type: 'field_number', name: 'AMT', value: 0.8, min: 0, max: 1 }],
    output: null,
    colour: 260,
    tooltip: 'Create a distortion effect',
  },
  {
    type: 'audio_connect',
    message0: 'connect %1 to %2',
    args0: [
      { type: 'input_value', name: 'FROM' },
      { type: 'input_value', name: 'TO' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Connect instrument to an effect',
  },

  // ── Audio Visualizer ───────────────────────────────────────────────────────
  {
    type: 'audio_viz',
    message0: 'visualize %1 mode %2',
    args0: [
      { type: 'input_value', name: 'SOURCE' },
      {
        type: 'field_dropdown',
        name: 'MODE',
        options: [
          ['bars', 'bars'],
          ['wave', 'wave'],
          ['ring', 'ring'],
        ],
      },
    ],
    output: null,
    colour: 260,
    tooltip: 'Create an audio visualizer — returns AudioViz. Connect to start/stop/opacity/shader.',
  },
  {
    type: 'audio_viz_start',
    message0: 'start visualizer %1',
    args0: [{ type: 'input_value', name: 'VIZ' }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Start an AudioViz drawing to the canvas',
  },
  {
    type: 'audio_viz_stop',
    message0: 'stop visualizer %1',
    args0: [{ type: 'input_value', name: 'VIZ' }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Stop an AudioViz',
  },
  {
    type: 'audio_viz_shader',
    message0: 'visualizer %1 shader %2',
    args0: [
      { type: 'input_value', name: 'VIZ' },
      {
        type: 'field_dropdown',
        name: 'PRESET',
        options: [
          ['thermal', 'thermal'],
          ['cool', 'cool'],
          ['rainbow', 'rainbow'],
          ['mono', 'mono'],
          ['neon', 'neon'],
        ],
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Apply a named shader preset to an AudioViz — thermal, cool, rainbow, mono, neon',
  },

  // ── Audio Mic / Speech ─────────────────────────────────────────────────────
  {
    type: 'audio_level',
    message0: 'mic level',
    output: 'Number',
    colour: 260,
    tooltip: 'Live mic amplitude 0–1 (RMS). Enable mic in toolbar first.',
  },
  {
    type: 'audio_on_level',
    message0: 'when mic louder than %1',
    args0: [
      { type: 'field_number', name: 'THRESHOLD', value: 0.6, min: 0, max: 1, precision: 0.01 },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Run code when mic amplitude exceeds threshold (0–1). Enable mic in toolbar first.',
  },
  {
    type: 'audio_on_word',
    message0: 'when word %1 spoken',
    args0: [{ type: 'field_input', name: 'WORD', text: 'hello' }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Run code when a specific word is spoken. Uses Web Speech API (Chrome/Edge).',
  },
  {
    type: 'audio_say',
    message0: 'say %1',
    args0: [{ type: 'field_input', name: 'TEXT', text: 'hello' }],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Speak text using browser text-to-speech.',
  },

  // ── Raw JS passthrough (ADR 037) ─────────────────────────────────────────────
  // Holds any statement that has no dedicated block — emitted verbatim by the
  // generator. js-to-blocks wraps unrecognized statements (e.g. Strudel note()/s()
  // calls) in this instead of dropping them, so text↔blocks round-trips losslessly.
  {
    type: 'js_raw',
    message0: 'JS %1',
    args0: [{ type: 'field_multilinetext', name: 'CODE', text: '' }],
    previousStatement: null,
    nextStatement: null,
    colour: 0,
    tooltip:
      'Raw JavaScript with no dedicated block (e.g. a Strudel pattern). Preserved verbatim so switching between text and blocks never loses code. Edit as text.',
  },

  // ── Shader ─────────────────────────────────────────────────────────────────
  // Creator blocks (output = Shader) — plug into start / stop / opacity / set_uniform
  {
    type: 'shader_preset',
    message0: '%1 shader',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PRESET',
        options: [
          ['gradient', 'gradient'],
          ['plasma', 'plasma'],
          ['waves', 'waves'],
          ['circles', 'circles'],
          ['noise', 'noise'],
        ],
      },
    ],
    output: null,
    colour: 330,
    tooltip: 'Create a preset shader — connect to "start shader"',
  },
  {
    type: 'shader_new',
    message0: 'new shader z %1 opacity %2',
    args0: [
      { type: 'field_number', name: 'Z', value: 30 },
      { type: 'field_number', name: 'OPACITY', value: 1.0, min: 0, max: 1 },
    ],
    output: null,
    colour: 330,
    tooltip: 'Create a custom shader — connect to "start shader"',
  },
  {
    type: 'shader_wgsl',
    message0: 'wgsl shader %1',
    args0: [{ type: 'field_input', name: 'BODY', text: 'return vec4f(uv.x, uv.y, 0.5, 1.0);' }],
    output: null,
    colour: 330,
    tooltip: 'Custom WGSL fragment body — connects to start/stop/opacity blocks.',
  },
  {
    type: 'shader_js_fn',
    message0: 'js shader %1',
    args0: [
      {
        type: 'field_input',
        name: 'BODY',
        text: '({ uv, time }) => {\n  return [uv.x, uv.y, 0.5, 1.0];\n}',
      },
    ],
    output: null,
    colour: 330,
    tooltip: 'JS arrow function shader — written as plain JS, compiled to WGSL at runtime.',
  },
  // Decomposed JS shader fn — shader body as nested statement blocks
  {
    type: 'shader_fn_body',
    message0: 'shader fn %1',
    args0: [{ type: 'input_statement', name: 'BODY' }],
    output: null,
    colour: 330,
    tooltip: 'Shader function body — use math/variable/return blocks inside.',
  },
  {
    type: 'shader_return_rgba',
    message0: 'return  r %1  g %2  b %3  a %4',
    args0: [
      { type: 'input_value', name: 'R' },
      { type: 'input_value', name: 'G' },
      { type: 'input_value', name: 'B' },
      { type: 'input_value', name: 'A' },
    ],
    previousStatement: null,
    colour: 330,
    tooltip: 'Return RGBA color from the shader.',
  },
  // Shader math — custom blocks that emit radians (Blockly's built-in trig converts degrees)
  {
    type: 'shader_math_trig',
    message0: '%1 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'OP',
        options: [
          ['sin', 'sin'],
          ['cos', 'cos'],
          ['tan', 'tan'],
          ['asin', 'asin'],
          ['acos', 'acos'],
          ['atan', 'atan'],
        ],
      },
      { type: 'input_value', name: 'ARG' },
    ],
    output: 'Number',
    colour: 230,
    tooltip: 'Trig function in radians (not degrees).',
  },
  {
    type: 'shader_math_fn',
    message0: '%1 %2 %3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'OP',
        options: [
          ['abs', 'abs'],
          ['sqrt', 'sqrt'],
          ['floor', 'floor'],
          ['ceil', 'ceil'],
          ['round', 'round'],
          ['sign', 'sign'],
          ['exp', 'exp'],
          ['log', 'log'],
          ['min', 'min'],
          ['max', 'max'],
        ],
      },
      { type: 'input_value', name: 'ARG' },
      { type: 'input_value', name: 'ARG2' },
    ],
    output: 'Number',
    colour: 230,
    tooltip: 'Math function — ARG2 used by min/max.',
  },
  // Shader parameter value blocks
  ...[
    'uv_x:uv.x',
    'uv_y:uv.y',
    'time:time',
    'mouse_x:mouse.x',
    'mouse_y:mouse.y',
    'res_x:res.x',
    'res_y:res.y',
    'custom_x:custom.x',
    'custom_y:custom.y',
    'custom_z:custom.z',
    'custom_w:custom.w',
  ].map((s) => {
    const [key, label] = s.split(':');
    return {
      type: `shader_param_${key}`,
      message0: label,
      output: 'Number',
      colour: 300,
      tooltip: `Shader input: ${label}`,
    };
  }),
  {
    type: 'shader_camera_effect',
    message0: 'camera %1 shader %2',
    args0: [
      { type: 'input_value', name: 'CAM' },
      {
        type: 'field_dropdown',
        name: 'EFFECT',
        options: [
          ['greyscale', 'greyscale'],
          ['invert', 'invert'],
          ['channel swap', 'channel_swap'],
          ['posterize', 'posterize'],
          ['scanlines', 'scanlines'],
        ],
      },
    ],
    output: null,
    colour: 330,
    tooltip:
      'Camera shader — leave cam empty for toolbar camera, or plug in a Camera.open() stream. Connect to start/stop/opacity.',
  },
  {
    type: 'shader_video_effect',
    message0: 'video %1 shader %2',
    args0: [
      { type: 'input_value', name: 'VIDEO' },
      {
        type: 'field_dropdown',
        name: 'EFFECT',
        options: [
          ['greyscale', 'greyscale'],
          ['invert', 'invert'],
          ['channel swap', 'channel_swap'],
          ['posterize', 'posterize'],
          ['scanlines', 'scanlines'],
        ],
      },
    ],
    output: null,
    colour: 330,
    tooltip: 'Create a video shader — connect to start/stop/opacity.',
  },
  {
    type: 'shader_window_effect',
    message0: 'window %1 shader %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'WIN',
        options: [
          ['editor', 'editor'],
          ['console', 'console'],
          ['canvas', 'canvas'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'EFFECT',
        options: [
          ['greyscale', 'greyscale'],
          ['invert', 'invert'],
          ['channel swap', 'channel_swap'],
          ['posterize', 'posterize'],
          ['scanlines', 'scanlines'],
        ],
      },
    ],
    output: null,
    colour: 330,
    tooltip: 'Capture an IDE window and apply a shader effect — connect to "start shader".',
  },
  {
    type: 'shader_mic_viz',
    message0: 'mic viz shader %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'EFFECT',
        options: [
          ['greyscale', 'greyscale'],
          ['invert', 'invert'],
          ['channel swap', 'channel_swap'],
          ['posterize', 'posterize'],
          ['scanlines', 'scanlines'],
        ],
      },
    ],
    output: null,
    colour: 330,
    tooltip: 'Apply a shader effect to the mic visualizer canvas — connect to "start shader".',
  },
  // Action blocks (statements) — take a Shader input
  {
    type: 'shader_start',
    message0: 'start shader %1',
    args0: [{ type: 'input_value', name: 'SHADER' }],
    previousStatement: null,
    nextStatement: null,
    colour: 330,
  },
  {
    type: 'shader_stop',
    message0: 'stop shader %1',
    args0: [{ type: 'input_value', name: 'SHADER' }],
    previousStatement: null,
    nextStatement: null,
    colour: 330,
  },
  {
    type: 'shader_opacity',
    message0: 'set shader %1 opacity %2',
    args0: [
      { type: 'input_value', name: 'SHADER' },
      { type: 'field_number', name: 'OPACITY', value: 0.5, min: 0, max: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 330,
  },
  {
    type: 'shader_set_uniform',
    message0: 'set shader %1 channel %2 to %3',
    args0: [
      { type: 'input_value', name: 'SHADER' },
      {
        type: 'field_dropdown',
        name: 'CHANNEL',
        options: [
          ['0', '0'],
          ['1', '1'],
          ['2', '2'],
          ['3', '3'],
        ],
      },
      { type: 'field_number', name: 'VALUE', value: 0.5, min: 0, max: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 330,
    tooltip: "Write a value into the shader's custom uniform (readable as custom.x .y .z .w)",
  },

  // ── Vision ─────────────────────────────────────────────────────────────────
  {
    type: 'vision_on_gesture',
    message0: 'when gesture %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'GESTURE',
        options: [
          ['👍 Thumb Up', 'Thumb_Up'],
          ['👎 Thumb Down', 'Thumb_Down'],
          ['✋ Open Palm', 'Open_Palm'],
          ['✊ Closed Fist', 'Closed_Fist'],
          ['☝️ Pointing Up', 'Pointing_Up'],
          ['✌️ Victory', 'Victory'],
          ['🤟 I Love You', 'ILoveYou'],
        ],
      },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Run code when a hand gesture is first detected',
  },
  {
    type: 'vision_on_expression',
    message0: 'when face %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'EXPR',
        options: [
          ['😊 smiles', 'smile'],
          ['😮 is surprised', 'surprise'],
          ['😦 frowns', 'frown'],
          ['😮 mouth open', 'mouth_open'],
        ],
      },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 180,
  },
  {
    type: 'vision_gesture',
    message0: 'current gesture',
    output: 'String',
    colour: 180,
    tooltip: 'Current hand gesture string or null',
  },
  {
    type: 'vision_face_detected',
    message0: 'face detected',
    output: 'Boolean',
    colour: 180,
    tooltip: 'True if a face is currently visible',
  },
  {
    type: 'vision_nearest',
    message0: 'nearest %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'LABEL',
        options: [
          ['person', 'person'],
          ['cat', 'cat'],
          ['dog', 'dog'],
          ['chair', 'chair'],
          ['bottle', 'bottle'],
          ['cell phone', 'cell phone'],
          ['laptop', 'laptop'],
          ['book', 'book'],
        ],
      },
    ],
    output: null,
    colour: 180,
    tooltip: 'Nearest detected object — {label, cx, cy, confidence} or null',
  },
  {
    type: 'vision_gaze',
    message0: 'gaze',
    output: null,
    colour: 180,
    tooltip: 'Where the user looks — {x, y, dir, blink, leftClosed, rightClosed, vx, vy} or null',
  },
  {
    type: 'vision_on_gaze',
    message0: 'when looking %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'DIR',
        options: [
          ['⬅️ left', 'left'],
          ['➡️ right', 'right'],
          ['⬆️ up', 'up'],
          ['⬇️ down', 'down'],
          ['🎯 center', 'center'],
        ],
      },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Run code when gaze direction enters this zone (no calibration needed)',
  },
  {
    type: 'vision_on_blink',
    message0: 'when blink',
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Run code when both eyes blink',
  },

  // ── Draw ───────────────────────────────────────────────────────────────────
  {
    type: 'draw_bg',
    message0: 'background color %1',
    args0: [{ type: 'field_input', name: 'COLOR', text: '#111111' }],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Fill entire canvas with a color',
  },
  {
    type: 'draw_line',
    message0: 'line from x %1 y %2 to x %3 y %4 color %5 thickness %6',
    args0: [
      { type: 'field_number', name: 'X1', value: 0 },
      { type: 'field_number', name: 'Y1', value: 0 },
      { type: 'field_number', name: 'X2', value: 400 },
      { type: 'field_number', name: 'Y2', value: 400 },
      { type: 'field_input', name: 'COLOR', text: 'white' },
      { type: 'field_number', name: 'THICKNESS', value: 2, min: 0.5 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw a line between two points',
  },
  {
    type: 'draw_text',
    message0: 'text %1 at x %2 y %3 size %4 color %5',
    args0: [
      { type: 'field_input', name: 'STR', text: 'hello' },
      { type: 'field_number', name: 'X', value: 100 },
      { type: 'field_number', name: 'Y', value: 100 },
      { type: 'field_number', name: 'SIZE', value: 32, min: 1 },
      { type: 'field_input', name: 'COLOR', text: 'white' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw text on the canvas',
  },
  {
    type: 'draw_text_rich',
    message0: 'text %1 at x %2 y %3 size %4 color %5 stroke %6 shadow %7',
    args0: [
      { type: 'field_input', name: 'STR', text: 'hello' },
      { type: 'field_number', name: 'X', value: 100 },
      { type: 'field_number', name: 'Y', value: 200 },
      { type: 'field_number', name: 'SIZE', value: 48, min: 1 },
      { type: 'field_input', name: 'COLOR', text: 'white' },
      { type: 'field_checkbox', name: 'STROKE', checked: false },
      { type: 'field_checkbox', name: 'SHADOW', checked: true },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw styled text — optional stroke outline and drop shadow',
  },
  {
    type: 'draw_alpha',
    message0: 'draw transparency %1',
    args0: [{ type: 'field_number', name: 'ALPHA', value: 0.5, min: 0, max: 1 }],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip:
      'Set global drawing opacity (0=invisible, 1=opaque). Affects all draw calls after this.',
  },
  {
    type: 'draw_reset',
    message0: 'reset draw state',
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Reset draw transparency, blend mode, and transforms to defaults',
  },

  // ── Canvas ─────────────────────────────────────────────────────────────────
  {
    type: 'canvas_fill_rect',
    message0: 'fill rect x %1 y %2 w %3 h %4 color %5',
    args0: [
      { type: 'field_number', name: 'X', value: 0 },
      { type: 'field_number', name: 'Y', value: 0 },
      { type: 'field_number', name: 'W', value: 100 },
      { type: 'field_number', name: 'H', value: 100 },
      { type: 'field_input', name: 'COLOR', text: 'red' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw a filled rectangle on canvas layer 0',
  },
  {
    type: 'canvas_fill_circle',
    message0: 'fill circle x %1 y %2 r %3 color %4',
    args0: [
      { type: 'field_number', name: 'X', value: 200 },
      { type: 'field_number', name: 'Y', value: 200 },
      { type: 'field_number', name: 'R', value: 50 },
      { type: 'field_input', name: 'COLOR', text: 'blue' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
  },
  {
    type: 'canvas_clear',
    message0: 'clear canvas',
    previousStatement: null,
    nextStatement: null,
    colour: 60,
  },

  // ── Windowed Canvas surface (ADR 038) ───────────────────────────────────────
  {
    type: 'canvas_new',
    message0: 'new Canvas width %1 height %2 title %3',
    args0: [
      { type: 'field_number', name: 'W', value: 1600 },
      { type: 'field_number', name: 'H', value: 900 },
      { type: 'field_input', name: 'TITLE', text: 'Sketch' },
    ],
    output: null,
    colour: 200,
    tooltip:
      'Create a window-scoped drawing surface at its own size. Plug into a variable, then use the canvas background / circle / on-pointer blocks.',
  },
  {
    type: 'canvas_surface_bg',
    message0: 'canvas %1 background %2',
    args0: [
      { type: 'input_value', name: 'CANVAS' },
      { type: 'field_input', name: 'COLOR', text: '#0a0a18' },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Fill a Canvas surface with a color.',
  },
  {
    type: 'canvas_surface_circle',
    message0: 'canvas %1 circle x %2 y %3 r %4 color %5',
    args0: [
      { type: 'input_value', name: 'CANVAS' },
      { type: 'input_value', name: 'X', check: 'Number' },
      { type: 'input_value', name: 'Y', check: 'Number' },
      { type: 'field_number', name: 'R', value: 20 },
      { type: 'field_input', name: 'COLOR', text: '#ffffff' },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Draw a filled circle on a Canvas surface.',
  },
  {
    type: 'canvas_on',
    message0: 'on canvas %1 pointer %2',
    args0: [
      { type: 'input_value', name: 'CANVAS' },
      {
        type: 'field_dropdown',
        name: 'EVENT',
        options: [
          ['down', 'down'],
          ['move', 'move'],
          ['up', 'up'],
        ],
      },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip:
      'Run code on a Canvas pointer event. Read the live position with the canvas pointer block.',
  },
  {
    type: 'canvas_pointer',
    message0: 'canvas %1 pointer %2',
    args0: [
      { type: 'input_value', name: 'CANVAS' },
      {
        type: 'field_dropdown',
        name: 'AXIS',
        options: [
          ['x', 'x'],
          ['y', 'y'],
        ],
      },
    ],
    inputsInline: true,
    output: 'Number',
    colour: 200,
    tooltip: 'Read the live pointer x or y, in canvas coordinates.',
  },
  {
    type: 'canvas_blur',
    message0: 'blur layer %1 by %2 px',
    args0: [
      { type: 'field_number', name: 'Z', value: 0 },
      { type: 'field_number', name: 'AMT', value: 5, min: 0 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
  },
  {
    type: 'canvas_layer_opacity',
    message0: 'set layer %1 opacity %2',
    args0: [
      { type: 'field_number', name: 'Z', value: 0 },
      { type: 'field_number', name: 'OPACITY', value: 0.5, min: 0, max: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
  },
  {
    type: 'canvas_blend_mode',
    message0: 'layer %1 blend mode %2',
    args0: [
      { type: 'field_number', name: 'Z', value: 1 },
      {
        type: 'field_dropdown',
        name: 'MODE',
        options: [
          ['screen', 'screen'],
          ['multiply', 'multiply'],
          ['overlay', 'overlay'],
          ['difference', 'difference'],
          ['lighten', 'lighten'],
          ['darken', 'darken'],
          ['hard-light', 'hard-light'],
          ['soft-light', 'soft-light'],
          ['exclusion', 'exclusion'],
          ['color-burn', 'color-burn'],
        ],
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Set CSS mix-blend-mode on a layer — composites it with layers below',
  },
  {
    type: 'draw_pixelate',
    message0: 'pixelate layer %1 block size %2',
    args0: [
      { type: 'field_number', name: 'Z', value: 0 },
      { type: 'field_number', name: 'BLOCK', value: 8, min: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw a blocky pixelated copy of a canvas layer onto the main canvas',
  },

  {
    type: 'draw_backdrop',
    message0: 'draw backdrop url/source %1 fit %2',
    args0: [
      { type: 'field_input', name: 'SRC', text: 'camera' },
      {
        type: 'field_dropdown',
        name: 'FIT',
        options: [
          ['cover', 'cover'],
          ['contain', 'contain'],
          ['stretch', 'stretch'],
        ],
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip:
      'Render an image, video, camera, or URL as a layer below all draw calls. Source: a URL string, "camera", or a variable. fit: cover/contain/stretch.',
  },

  // ── Media ──────────────────────────────────────────────────────────────────
  {
    type: 'media_video',
    message0: 'video from %1',
    args0: [{ type: 'field_input', name: 'URL', text: 'https://example.com/clip.mp4' }],
    output: null,
    colour: 45,
    tooltip: 'Create a video layer — call play() on it to start',
  },
  {
    type: 'media_video_play',
    message0: 'play video %1',
    args0: [{ type: 'input_value', name: 'VIDEO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 45,
  },
  {
    type: 'media_video_stop',
    message0: 'stop video %1',
    args0: [{ type: 'input_value', name: 'VIDEO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 45,
  },
  {
    type: 'media_image_layer',
    message0: 'image layer from %1',
    args0: [{ type: 'field_input', name: 'URL', text: 'https://example.com/photo.jpg' }],
    output: null,
    colour: 45,
    tooltip: 'Load image as canvas overlay — awaitable',
  },

  // ── Windows ────────────────────────────────────────────────────────────────
  {
    type: 'wm_layout',
    message0: 'layout %1',
    args0: [{ type: 'field_dropdown', name: 'LAYOUT', options: [['split', 'split']] }],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Switch to a named tiling layout',
  },
  {
    type: 'wm_show_hide',
    message0: '%1 window %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'ACTION',
        options: [
          ['show', 'show'],
          ['hide', 'hide'],
          ['toggle', 'toggle'],
          ['focus', 'focus'],
          ['maximize', 'maximize'],
          ['restore', 'restore'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'WIN',
        options: [
          ['editor', 'win-editor'],
          ['output', 'win-canvas'],
          ['console', 'win-console'],
          ['toolkit', 'win-toolkit'],
          ['camera', 'win-camera'],
          ['mic', 'win-mic'],
        ],
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
  },
  {
    type: 'wm_move',
    message0: 'move window %1 x %2 y %3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'WIN',
        options: [
          ['editor', 'win-editor'],
          ['output', 'win-canvas'],
          ['console', 'win-console'],
          ['toolkit', 'win-toolkit'],
          ['camera', 'win-camera'],
          ['mic', 'win-mic'],
        ],
      },
      { type: 'field_number', name: 'X', value: 0 },
      { type: 'field_number', name: 'Y', value: 0 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
  },
  {
    type: 'wm_resize_win',
    message0: 'resize window %1 w %2 h %3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'WIN',
        options: [
          ['editor', 'win-editor'],
          ['output', 'win-canvas'],
          ['console', 'win-console'],
          ['toolkit', 'win-toolkit'],
          ['camera', 'win-camera'],
          ['mic', 'win-mic'],
        ],
      },
      { type: 'field_number', name: 'W', value: 640 },
      { type: 'field_number', name: 'H', value: 480 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
  },
  {
    type: 'wm_close_win',
    message0: 'close window %1',
    args0: [{ type: 'input_value', name: 'ID' }],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Close a spawned window by id',
  },
  {
    type: 'wm_set_z',
    message0: 'set window %1 z-index %2',
    args0: [
      { type: 'input_value', name: 'ID' },
      { type: 'field_number', name: 'Z', value: 200 },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Set CSS z-index stacking order on a window',
  },
  {
    type: 'wm_set_opacity',
    message0: 'set window %1 opacity %2',
    args0: [
      { type: 'input_value', name: 'ID' },
      { type: 'field_number', name: 'V', value: 0.5, min: 0, max: 1, precision: 0.01 },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Set CSS opacity on a window (0=transparent, 1=opaque)',
  },
  {
    type: 'wm_spawn_html',
    message0: 'spawn html window %1 html %2 w %3 h %4',
    args0: [
      { type: 'field_input', name: 'TITLE', text: 'panel' },
      { type: 'field_input', name: 'HTML', text: '<p>hello</p>' },
      { type: 'field_number', name: 'W', value: 320 },
      { type: 'field_number', name: 'H', value: 240 },
    ],
    output: 'String',
    colour: 200,
    tooltip: 'Spawn an HTML window — returns its id',
  },
  {
    type: 'wm_spawn_camera',
    message0: 'spawn camera window %1 w %2 h %3',
    args0: [
      { type: 'field_input', name: 'TITLE', text: 'camera' },
      { type: 'field_number', name: 'W', value: 320 },
      { type: 'field_number', name: 'H', value: 240 },
    ],
    output: 'String',
    colour: 200,
    tooltip: 'Spawn a window mirroring the camera feed — returns its id',
  },
  {
    type: 'wm_spawn_canvas',
    message0: 'spawn canvas z %1 window %2 w %3 h %4',
    args0: [
      { type: 'field_number', name: 'Z', value: 0 },
      { type: 'field_input', name: 'TITLE', text: 'canvas' },
      { type: 'field_number', name: 'W', value: 640 },
      { type: 'field_number', name: 'H', value: 480 },
    ],
    output: 'String',
    colour: 200,
    tooltip: 'Spawn a window mirroring canvas layer z — returns its id',
  },
  {
    type: 'wm_spawn_image',
    message0: 'spawn image %1 title %2 w %3 h %4',
    args0: [
      { type: 'input_value', name: 'SRC' },
      { type: 'field_input', name: 'TITLE', text: 'image' },
      { type: 'field_number', name: 'W', value: 480 },
      { type: 'field_number', name: 'H', value: 360 },
    ],
    inputsInline: true,
    output: 'String',
    colour: 200,
    tooltip: 'Spawn an image window from a URL or blob URL — returns its id',
  },
  {
    type: 'wm_spawn_video',
    message0: 'spawn video %1 title %2 w %3 h %4',
    args0: [
      { type: 'input_value', name: 'SRC' },
      { type: 'field_input', name: 'TITLE', text: 'video' },
      { type: 'field_number', name: 'W', value: 640 },
      { type: 'field_number', name: 'H', value: 480 },
    ],
    inputsInline: true,
    output: 'String',
    colour: 200,
    tooltip: 'Spawn a video window from a URL or blob URL — returns its id',
  },
  {
    type: 'wm_spawn_shader',
    message0: 'spawn shader %1 title %2 w %3 h %4',
    args0: [
      { type: 'input_value', name: 'SHADER' },
      { type: 'field_input', name: 'TITLE', text: 'shader' },
      { type: 'field_number', name: 'W', value: 640 },
      { type: 'field_number', name: 'H', value: 480 },
    ],
    inputsInline: true,
    output: 'String',
    colour: 200,
    tooltip: "Spawn a window mirroring a shader's output — returns its id",
  },
  {
    type: 'wm_pick_file',
    message0: 'pick file key %1',
    args0: [{ type: 'field_input', name: 'KEY', text: 'myFile' }],
    output: 'String',
    colour: 200,
    tooltip: 'Pick a file via browser — cached by key, no re-prompt. Returns blob URL.',
  },
  {
    type: 'wm_browse',
    message0: 'browse dir key %1 w %2 h %3',
    args0: [
      { type: 'field_input', name: 'KEY', text: 'myDir' },
      { type: 'field_number', name: 'W', value: 260, min: 100 },
      { type: 'field_number', name: 'H', value: 400, min: 100 },
    ],
    message1: 'on select url %1 filename %2 do %3',
    args1: [
      { type: 'field_variable', name: 'URL_VAR', variable: 'url' },
      { type: 'field_variable', name: 'NAME_VAR', variable: 'filename' },
      { type: 'input_statement', name: 'DO' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip:
      'Open a directory file browser. Click a file to run the DO statements with url and filename set.',
  },

  // ── Drumpad ────────────────────────────────────────────────────────────────
  {
    type: 'drumpad_open',
    message0: 'drum pad title %1 bpm %2',
    args0: [
      { type: 'field_input', name: 'TITLE', text: 'Drum Pad' },
      { type: 'field_number', name: 'BPM', value: 120, min: 40, max: 300 },
    ],
    output: null,
    colour: 20,
    tooltip:
      'Open a drumpad window and return the dp object. Connect to on-pad/on-hit/on-step blocks or call dp.pattern(), dp.bpm().',
  },
  {
    type: 'drumpad_on_pad',
    message0: 'on drumpad %1 pad %2',
    args0: [
      { type: 'input_value', name: 'DP' },
      {
        type: 'field_dropdown',
        name: 'VOICE',
        options: [
          ['Kick (0)', '0'],
          ['Snare (1)', '1'],
          ['HH Cl (2)', '2'],
          ['HH Op (3)', '3'],
          ['Clap (4)', '4'],
          ['Tom L (5)', '5'],
          ['Tom H (6)', '6'],
          ['Cymbal (7)', '7'],
        ],
      },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 20,
    tooltip:
      'Run code when a specific drum pad is hit. Fires for pad clicks, key presses, and sequencer steps.',
  },
  {
    type: 'drumpad_on_hit',
    message0: 'on drumpad %1 any hit',
    args0: [{ type: 'input_value', name: 'DP' }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 20,
    tooltip: 'Run code whenever any drum pad fires. Use with dp.signal() to get a value.',
  },
  {
    type: 'drumpad_on_step',
    message0: 'on drumpad %1 sequencer step',
    args0: [{ type: 'input_value', name: 'DP' }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 20,
    tooltip: 'Run code once per sequencer step (0-15) while the drumpad is playing.',
  },
  {
    type: 'drumpad_signal',
    message0: 'drumpad %1 pad %2 signal decay %3 ms',
    args0: [
      { type: 'input_value', name: 'DP' },
      {
        type: 'field_dropdown',
        name: 'VOICE',
        options: [
          ['any', 'null'],
          ['Kick (0)', '0'],
          ['Snare (1)', '1'],
          ['HH Cl (2)', '2'],
          ['HH Op (3)', '3'],
          ['Clap (4)', '4'],
          ['Tom L (5)', '5'],
          ['Tom H (6)', '6'],
          ['Cymbal (7)', '7'],
        ],
      },
      { type: 'field_number', name: 'DECAY', value: 250, min: 10, max: 5000 },
    ],
    output: null,
    colour: 20,
    tooltip:
      'Return a live 0–1 decaying-pulse signal for a pad (or any pad). .value jumps to 1 on each hit and decays to 0. Use with shader.set() or draw.',
  },

  // ── Piano ──────────────────────────────────────────────────────────────────
  {
    type: 'piano_open',
    message0: 'piano title %1 preset %2',
    args0: [
      { type: 'field_input', name: 'TITLE', text: 'Piano' },
      {
        type: 'field_dropdown',
        name: 'PRESET',
        options: [
          ['electric', 'electric'],
          ['grand', 'grand'],
          ['organ', 'organ'],
          ['pluck', 'pluck'],
          ['pad', 'pad'],
          ['bass', 'bass'],
        ],
      },
    ],
    output: null,
    colour: 20,
    tooltip:
      'Open a piano widget and return the piano object. Connect to on-note/on-key/on-step blocks or use p.signal().',
  },
  {
    type: 'piano_on_note',
    message0: 'on piano %1 any note',
    args0: [{ type: 'input_value', name: 'PIANO' }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 20,
    tooltip: 'Run code whenever any piano key is played (mouse, keyboard, or sequencer).',
  },
  {
    type: 'piano_on_step',
    message0: 'on piano %1 sequencer step',
    args0: [{ type: 'input_value', name: 'PIANO' }],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 20,
    tooltip: 'Run code once per sequencer step (0-15) while the piano sequencer is playing.',
  },
  {
    type: 'piano_signal',
    message0: 'piano %1 signal decay %2 ms',
    args0: [
      { type: 'input_value', name: 'PIANO' },
      { type: 'field_number', name: 'DECAY', value: 300, min: 10, max: 5000 },
    ],
    output: null,
    colour: 20,
    tooltip:
      'Return a live 0–1 decaying-pulse signal for any note on the piano. .value jumps to 1 on each hit and decays to 0.',
  },

  // ── PIXI ───────────────────────────────────────────────────────────────────
  {
    type: 'pixi_graphics_circle',
    message0: 'pixi circle x %1 y %2 r %3 color %4',
    args0: [
      { type: 'field_number', name: 'X', value: 400 },
      { type: 'field_number', name: 'Y', value: 225 },
      { type: 'field_number', name: 'R', value: 60 },
      { type: 'field_input', name: 'COLOR', text: '0x4488ff' },
    ],
    output: null,
    colour: 290,
    tooltip:
      'Create a PIXI Graphics circle — returns a Graphics object. Add to stage with "add to stage".',
  },
  {
    type: 'pixi_graphics_rect',
    message0: 'pixi rect x %1 y %2 w %3 h %4 color %5',
    args0: [
      { type: 'field_number', name: 'X', value: 300 },
      { type: 'field_number', name: 'Y', value: 150 },
      { type: 'field_number', name: 'W', value: 200 },
      { type: 'field_number', name: 'H', value: 150 },
      { type: 'field_input', name: 'COLOR', text: '0xff6600' },
    ],
    output: null,
    colour: 290,
    tooltip: 'Create a PIXI Graphics filled rectangle — returns Graphics object.',
  },
  {
    type: 'pixi_text',
    message0: 'pixi text %1 x %2 y %3 size %4 color %5',
    args0: [
      { type: 'field_input', name: 'STR', text: 'hello pixi' },
      { type: 'field_number', name: 'X', value: 100 },
      { type: 'field_number', name: 'Y', value: 100 },
      { type: 'field_number', name: 'SIZE', value: 48, min: 1 },
      { type: 'field_input', name: 'COLOR', text: '#ffffff' },
    ],
    output: null,
    colour: 290,
    tooltip: 'Create a PIXI Text object — returns Text. Add to stage with "add to stage".',
  },
  {
    type: 'pixi_sprite',
    message0: 'pixi sprite from %1',
    args0: [{ type: 'field_input', name: 'URL', text: 'https://example.com/hero.png' }],
    output: null,
    colour: 290,
    tooltip: 'Create a PIXI Sprite from a URL — returns Sprite. Add to stage.',
  },
  {
    type: 'pixi_add_to_stage',
    message0: 'add %1 to stage',
    args0: [{ type: 'input_value', name: 'OBJ' }],
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: 'Add a PIXI DisplayObject to the scene (Stage)',
  },
  {
    type: 'pixi_set_pos',
    message0: 'set %1 position x %2 y %3',
    args0: [
      { type: 'input_value', name: 'OBJ' },
      { type: 'field_number', name: 'X', value: 400 },
      { type: 'field_number', name: 'Y', value: 225 },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 290,
  },
  {
    type: 'pixi_set_rotation',
    message0: 'set %1 rotation %2 deg',
    args0: [
      { type: 'input_value', name: 'OBJ' },
      { type: 'field_number', name: 'DEG', value: 45 },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 290,
  },
  {
    type: 'pixi_set_alpha',
    message0: 'set %1 alpha %2',
    args0: [
      { type: 'input_value', name: 'OBJ' },
      { type: 'field_number', name: 'ALPHA', value: 0.5, min: 0, max: 1 },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 290,
  },
  {
    type: 'pixi_blur_filter',
    message0: 'blur %1 by %2 px',
    args0: [
      { type: 'input_value', name: 'OBJ' },
      { type: 'field_number', name: 'BLUR', value: 10, min: 0 },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: 'Apply a BlurFilter to a PIXI DisplayObject',
  },
  {
    type: 'pixi_tick',
    message0: 'on pixi tick',
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: 'Run code every PIXI animation frame — cleaned up on Stop. Use to animate sprites.',
  },
  {
    type: 'pixi_clear_stage',
    message0: 'clear PIXI stage',
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: 'Remove all objects from the PIXI stage',
  },

  // ── GLShader ───────────────────────────────────────────────────────────────
  {
    type: 'glshader_preset',
    message0: '%1 GLSL shader',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PRESET',
        options: [
          ['gradient', 'gradient'],
          ['plasma', 'plasma'],
          ['waves', 'waves'],
          ['circles', 'circles'],
          ['noise', 'noise'],
        ],
      },
    ],
    output: null,
    colour: 15,
    tooltip: 'Create a preset GLShader (WebGL/GLSL) — connect to "start GLShader"',
  },
  {
    type: 'glshader_body',
    message0: 'GLSL shader %1',
    args0: [
      {
        type: 'field_input',
        name: 'BODY',
        text: 'gl_FragColor = vec4(uv, sin(uTime)*0.5+0.5, 1.0);',
      },
    ],
    output: null,
    colour: 15,
    tooltip:
      'Custom GLSL fragment body. Pre-declared: uv (vec2 0-1), uTime, uMouse, uCustom, uResolution. Set gl_FragColor.',
  },
  {
    type: 'glshader_start',
    message0: 'start GLShader %1',
    args0: [{ type: 'input_value', name: 'SHADER' }],
    previousStatement: null,
    nextStatement: null,
    colour: 15,
  },
  {
    type: 'glshader_stop',
    message0: 'stop GLShader %1',
    args0: [{ type: 'input_value', name: 'SHADER' }],
    previousStatement: null,
    nextStatement: null,
    colour: 15,
  },
  {
    type: 'glshader_opacity',
    message0: 'set GLShader %1 opacity %2',
    args0: [
      { type: 'input_value', name: 'SHADER' },
      { type: 'field_number', name: 'OPACITY', value: 0.5, min: 0, max: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 15,
  },

  // ── Camera ─────────────────────────────────────────────────────────────────
  {
    type: 'camera_open',
    message0: 'open camera %1',
    args0: [{ type: 'field_number', name: 'INDEX', value: 0, min: 0 }],
    output: null,
    colour: 165,
    tooltip: 'Open a camera by index — returns a CameraStream. Use with shader video effect.',
  },
  {
    type: 'camera_stop',
    message0: 'stop camera %1',
    args0: [{ type: 'input_value', name: 'CAM' }],
    previousStatement: null,
    nextStatement: null,
    colour: 165,
    tooltip: 'Stop a CameraStream and release the device',
  },

  // ── Audio — filter / meter / chain / attack / release ──────────────────────
  {
    type: 'audio_filter',
    message0: '%1 filter freq %2 Hz Q %3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['lowpass', 'lowpass'],
          ['highpass', 'highpass'],
          ['bandpass', 'bandpass'],
          ['notch', 'notch'],
          ['allpass', 'allpass'],
        ],
      },
      { type: 'field_number', name: 'FREQ', value: 2000, min: 20, max: 20000 },
      { type: 'field_number', name: 'Q', value: 1, min: 0.1, max: 20 },
    ],
    output: null,
    colour: 260,
    tooltip: 'Create a filter effect — connect with chain or connect blocks',
  },
  {
    type: 'audio_meter',
    message0: 'meter',
    output: null,
    colour: 260,
    tooltip: 'Create a level meter — put it at the end of a chain to measure amplitude',
  },
  {
    type: 'audio_meter_value',
    message0: '%1 level (dB)',
    args0: [{ type: 'input_value', name: 'METER' }],
    output: 'Number',
    inputsInline: true,
    colour: 260,
    tooltip: 'Get current meter level in dB — use isFinite() check; -Infinity when silent',
  },
  {
    type: 'audio_chain',
    message0: 'chain %1 through %2 %3 %4',
    args0: [
      { type: 'input_value', name: 'SYNTH' },
      { type: 'input_value', name: 'FX1' },
      { type: 'input_value', name: 'FX2' },
      { type: 'input_value', name: 'FX3' },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip:
      'Route synth through up to 3 effects (FX2, FX3 optional) — e.g. filter → reverb → meter',
  },
  {
    type: 'audio_attack',
    message0: 'attack %1 on %2',
    args0: [
      { type: 'field_input', name: 'NOTE', text: 'C4' },
      { type: 'input_value', name: 'SYNTH' },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Trigger note attack (key-down) without release — pair with audio release block',
  },
  {
    type: 'audio_release',
    message0: 'release %1 on %2',
    args0: [
      { type: 'field_input', name: 'NOTE', text: 'C4' },
      { type: 'input_value', name: 'SYNTH' },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Trigger note release (key-up) — pairs with audio attack block',
  },

  // ── Draw — ring / rectStroke ───────────────────────────────────────────────
  {
    type: 'draw_ring',
    message0: 'ring x %1 y %2 r %3 color %4 thickness %5',
    args0: [
      { type: 'field_number', name: 'X', value: 400 },
      { type: 'field_number', name: 'Y', value: 225 },
      { type: 'field_number', name: 'R', value: 80 },
      { type: 'field_input', name: 'COLOR', text: 'white' },
      { type: 'field_number', name: 'T', value: 3, min: 0.5 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw a stroked circle (ring) — no fill',
  },
  {
    type: 'draw_rect_stroke',
    message0: 'rect outline x %1 y %2 w %3 h %4 color %5 thickness %6',
    args0: [
      { type: 'field_number', name: 'X', value: 100 },
      { type: 'field_number', name: 'Y', value: 100 },
      { type: 'field_number', name: 'W', value: 200 },
      { type: 'field_number', name: 'H', value: 120 },
      { type: 'field_input', name: 'COLOR', text: 'white' },
      { type: 'field_number', name: 'T', value: 2, min: 0.5 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 60,
    tooltip: 'Draw a stroked rectangle outline — no fill',
  },

  // ── Control — key with down + up handler ───────────────────────────────────
  {
    type: 'ctrl_onkey_char',
    message0: 'when key %1 pressed',
    args0: [{ type: 'field_input', name: 'KEY', text: 'a' }],
    message1: 'down %1',
    args1: [{ type: 'input_statement', name: 'DOWN' }],
    message2: 'up %1',
    args2: [{ type: 'input_statement', name: 'UP' }],
    previousStatement: null,
    nextStatement: null,
    colour: 120,
    tooltip:
      'Run code when any typed key is pressed/released — enter the key character (a, z, 1, Enter, ArrowUp…)',
  },

  // ── Three.js 3D ────────────────────────────────────────────────────────────
  {
    type: 'three_scene',
    message0: '3D scene z=%1',
    args0: [{ type: 'field_number', name: 'Z', value: 30 }],
    output: null,
    colour: 195,
    tooltip: 'Create a ThreeScene (WebGL 3D). Connect to "start 3D scene" to begin rendering.',
  },
  {
    type: 'three_start',
    message0: 'start 3D scene %1',
    args0: [{ type: 'input_value', name: 'SCENE' }],
    previousStatement: null,
    nextStatement: null,
    colour: 195,
    tooltip: 'Begin rendering a ThreeScene',
  },
  {
    type: 'three_tick',
    message0: '3D tick scene %1 dt=%2',
    args0: [
      { type: 'input_value', name: 'SCENE' },
      { type: 'field_variable', name: 'DT', variable: 'dt' },
    ],
    message1: 'do %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: 195,
    tooltip: 'Register a per-frame callback on the ThreeScene. dt = delta time in seconds.',
  },
  {
    type: 'three_box_mesh',
    message0: 'box mesh color %1',
    args0: [{ type: 'field_colour', name: 'COLOR', colour: '#4444ff' }],
    output: null,
    colour: 195,
    tooltip: 'Create a THREE.Mesh with BoxGeometry and MeshNormalMaterial',
  },
  {
    type: 'three_add',
    message0: 'add %1 to scene %2',
    args0: [
      { type: 'input_value', name: 'OBJ' },
      { type: 'input_value', name: 'SCENE' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 195,
    tooltip: 'Add a THREE.Object3D to a ThreeScene',
  },
  {
    type: 'three_rotate',
    message0: 'rotate %1 x+=%2 y+=%3',
    args0: [
      { type: 'input_value', name: 'OBJ' },
      { type: 'field_number', name: 'DX', value: 0.01 },
      { type: 'field_number', name: 'DY', value: 0.01 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 195,
    tooltip: 'Increment mesh rotation.x and rotation.y each frame',
  },
  {
    type: 'three_signal_graph',
    message0: 'show signal graph',
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: 'Open a window showing the live signal routing graph (sources → sinks)',
  },
]);
